server:
  port: 8081

spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hmdp?useSSL=false&allowPublicKeyRetrieval=true
    username: luzai
    password: '042022'
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8088
  task:
    scheduling:
      pool:
        size: 3



  redis:
    host: 127.0.0.1
    port: 6379
    # password: ''
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s


mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug
rocketmq:
  name-server: 172.25.202.49:9876
  producer:
    group: seckill-order-tx-group
    send-message-timeout: 3000
    retry-times-when-send-async-failed: 3
    retry-times-when-send-failed: 3

canal:
  destination: test # canal的集群名字，要与安装canal时设置的名称一致
  server: 127.0.0.1:11111 # canal服务地址
  username: canal # canal用户名
  password: canal # canal密码\



